env:
  - GO111MODULE=on
env_files:
  github_token: ~/.config/goreleaser/github_token
before:
  hooks:
    - go mod tidy
    - plugins/build.sh
builds:
  - id: linux
    main: ./cmd/web-msg-handler
    binary: web-msg-handler
    ldflags: -X github.com/Miguel-Dorta/web-msg-handler/internal.Version={{.Version}}
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

archives:
  - id: archiveLinux
    builds:
      - linux
    format: tar.gz
    files:
      - configs/**/*
      - examples/**/*
      - plugins/*.js
      - install.sh
      - LICENSE
      - README.md
