id="website2-mail"
recaptcha_secret="xkmBhVrYaB0NhtHpHgAWeTnLZpTSxCKs0gigByk5"
sender_type="mail"

[sender]
website_name="My personal website"
mailto="where_i_want_to_receive_the_forms@mailprovider2.org"
username="sender_address@mailprovider1.com"
password="bNRxxIPxX7kLrbN8WCG22VUmpBqVBGgLTnyLdjob"
hostname="smtp.mailprovider1.com"
port=587
