# Site ID, must be unique. This sender will be listening the URL /website1
id="website1"

# Google's reCAPTCHA v2 secret
recaptcha_secret="Uv38ByGCZU8WP18PmmIdcpVmx00QA3xNe7sEB9Hi"

# Sender to use, it must match the name of a plugin in the "plugins" folder
sender_type="telegram"

# Sender specific settings (in this case, telegram sender settings)
[sender]
website_name="My company's website" # Website name for identifying it
chat_id="9167320" # Chat ID. See: https://core.telegram.org/bots/api#chat
bot_token="123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11" # Bot token. See: https://core.telegram.org/bots/api#authorizing-your-bot
