id="website1-telegram"
recaptcha_secret="Uv38ByGCZU8WP18PmmIdcpVmx00QA3xNe7sEB9Hi"
sender_type="telegram"

[sender]
website_name="My company's website"
chatID="9167320"
botToken="123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
